/**
 * TYPE DEFINITIONS - Data Models for the Task Board
 *
 * These interfaces define the shape of our data
 * TypeScript uses these to provide type safety and autocomplete
 */

/**
 * TASK INTERFACE
 * Represents a single task/card in the Kanban board
 *
 * @property id - Unique identifier (generated by uuid)
 * @property title - Task description/content
 * @property columnId - ID of the column this task belongs to
 * @property position - Sort order within the column (0-indexed)
 */
export interface Task {
  id: string        // e.g., "task-1" or "550e8400-e29b-41d4-a716-446655440000"
  title: string     // e.g., "Implement user authentication"
  description?: string | null  // Optional task description
  columnId: string  // e.g., "todo", "in-progress", "done"
  position: number  // e.g., 0, 1, 2... (for future sorting functionality)
}

/**
 * COLUMN INTERFACE
 * Represents a column in the Kanban board
 *
 * @property id - Unique identifier (used as droppable ID)
 * @property title - Display name of the column
 * @property position - Sort order for columns (0-indexed)
 */
export interface Column {
  id: string        // e.g., "todo", "in-progress", "done"
  title: string     // e.g., "To Do", "In Progress", "Done"
  position: number  // e.g., 0, 1, 2... (determines column order)
}